import { heroMeadowJpg0 } from "./hero-meadow-0";
import { heroMeadowJpg1 } from "./hero-meadow-1";
import { heroMeadowJpg2 } from "./hero-meadow-2";
import { heroMeadowJpg3 } from "./hero-meadow-3";
import { heroMeadowJpg4 } from "./hero-meadow-4";
import { heroMeadowJpg5 } from "./hero-meadow-5";
import { heroMeadowJpg6 } from "./hero-meadow-6";
import { heroMeadowJpg7 } from "./hero-meadow-7";
import { heroMeadowJpg8 } from "./hero-meadow-8";
import { heroMeadowJpg9 } from "./hero-meadow-9";
import { heroMeadowJpg10 } from "./hero-meadow-10";
import { heroMeadowJpg11 } from "./hero-meadow-11";
export const heroMeadowJpg = heroMeadowJpg0 + heroMeadowJpg1 + heroMeadowJpg2 + heroMeadowJpg3 + heroMeadowJpg4 + heroMeadowJpg5 + heroMeadowJpg6 + heroMeadowJpg7 + heroMeadowJpg8 + heroMeadowJpg9 + heroMeadowJpg10 + heroMeadowJpg11;
